### ISSUE TITLE
Hii

### ISSUE THREAD

**Issue by jalal177** [zaenalrfn/zaenalarifin.github.io#1]

**Comment by zaenalrfn** [comment]
Hiii

Pada tanggal Sel, 15 Feb 2022 07.41, Jalaludin Ahmadi <
***@***.***> menulis:

**Comment by jalal177** [comment]
Folbek bos

**Comment by jalal177** [comment]
Oke

**Comment by zaenalrfn** [comment]
Oke

Pada tanggal Sel, 15 Feb 2022 07.59, Jalaludin Ahmadi <
***@***.***> menulis:
